services:
  flask-app:
    container_name: HealthyUI_Backend
    build: .
    ports: 
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - '.:/app'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${DATABASE_URL}

  mongodb:
    image: mongo:latest
    container_name: HealthyUI_DB 
    ports: 
     - 27017:27017 
    volumes:
      - mongo-data:/data/db

volumes: 
  mongo-data: 
