services:
  flask-app:
    container_name: HealthyUI_Backend
    build: .
    ports: 
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - '.:/app'
    #      environment:
    #      - MONGO_URI=mongodb://mongo:27017/healthy_ui 

  #  mongodb:
  #    image: mongo:latest
  #    container_name: HealthyUI_DB 
  #    ports: 
  #      - 27017:27017 
  #    environment: 
  #      MONGO_INITDB_DATABASE: healthy_ui
