export enum DataFetchState {
  LOADING, UNSUCCESSFUL_DATA_FETCH, SUCCESSFUL_DATA_FETCH, WRONG_PAGE, SUCCESSFUL_VIDEO_URL_LOADED, NO_DATA_TO_BE_LOADED
}
export enum QueryOption {
  FACT_CHECK, ANTI_SILOING
}

export enum Environment {
  PROD = "PROD", DEV = "DEV"
}
